# Generated by Django 2.0.13 on 2019-05-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField(default=0)),
                ('line_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('line', models.ManyToManyField(to='ekimei.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_cd', models.IntegerField(default=0)),
                ('station_g_cd', models.IntegerField(default=0)),
                ('station_name', models.CharField(max_length=200)),
                ('station_name_k', models.CharField(max_length=200)),
                ('station_name_r', models.CharField(max_length=200)),
                ('line_cd', models.IntegerField(default=0)),
                ('pref_cd', models.IntegerField(default=0)),
                ('post', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('open_ymd', models.CharField(max_length=200)),
                ('close_ymd', models.CharField(max_length=200)),
                ('e_status', models.IntegerField(default=0)),
                ('e_sort', models.IntegerField(default=0)),
            ],
        ),
    ]
