# Generated by Django 2.0.13 on 2019-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0002_auto_20190507_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cd', models.IntegerField(default=0)),
                ('company_cd', models.IntegerField(default=0)),
                ('line_name', models.CharField(max_length=200)),
                ('line_name_k', models.CharField(max_length=200)),
                ('line_name_h', models.CharField(max_length=200)),
                ('line_color_c', models.CharField(max_length=200)),
                ('line_color_t', models.CharField(max_length=200)),
                ('line_type', models.CharField(max_length=200)),
                ('lon', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('zoom', models.IntegerField(default=0)),
                ('e_status', models.IntegerField(default=0)),
                ('e_sort', models.IntegerField(default=0)),
            ],
        ),
    ]
