# Generated by Django 2.0.13 on 2019-05-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0004_creator_stationinmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinmovie',
            name='line_cd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Line'),
        ),
    ]
