# Generated by Django 2.0.13 on 2019-05-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0007_auto_20190507_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationinmovie',
            name='creator_a',
        ),
        migrations.AddField(
            model_name='stationinmovie',
            name='creator_a',
            field=models.ManyToManyField(related_name='audio_creator', to='ekimei.Creator'),
        ),
        migrations.RemoveField(
            model_name='stationinmovie',
            name='creator_m',
        ),
        migrations.AddField(
            model_name='stationinmovie',
            name='creator_m',
            field=models.ManyToManyField(related_name='movie_creator', to='ekimei.Creator'),
        ),
    ]
