# Generated by Django 2.1 on 2019-11-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekimei.Line', to_field='line_cd', verbose_name='路線'),
        ),
    ]
