# Generated by Django 2.0.13 on 2019-05-11 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0002_remove_stationinmovie_station_nonlist_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinmovie',
            name='station_nonlist_cd',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ekimei.NonListStation'),
        ),
    ]
