# Generated by Django 2.0.13 on 2019-05-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0005_stationinmovie_station_nonlist_cd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationinmovie',
            name='station_nonlist_cd',
        ),
    ]
