# Generated by Django 2.0.13 on 2019-05-11 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0007_stationinmovie_station_nonlist_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='stationinmovie',
            name='station_nonlist_cd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ekimei.NonListStation'),
        ),
    ]
