# Generated by Django 2.0.13 on 2019-05-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0008_auto_20190511_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='station',
            name='pref_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Prefecture'),
        ),
    ]
