# Generated by Django 2.0.13 on 2019-05-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0009_auto_20190512_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonliststation',
            name='add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nonliststation',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nonliststation',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nonliststation',
            name='pref_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Prefecture'),
        ),
        migrations.AlterField(
            model_name='station',
            name='add',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
