# Generated by Django 2.0.13 on 2019-05-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0010_auto_20190512_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonliststation',
            name='e_status',
            field=models.IntegerField(choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='station',
            name='add',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='station',
            name='close_ymd',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='廃止年月日'),
        ),
        migrations.AlterField(
            model_name='station',
            name='e_sort',
            field=models.IntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='station',
            name='e_status',
            field=models.IntegerField(choices=[(0, '運用中'), (1, '運用前'), (2, '廃止')], default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='station',
            name='line_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekimei.Line', to_field='line_cd', verbose_name='路線'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lon',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='station',
            name='open_ymd',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='開業年月日'),
        ),
        migrations.AlterField(
            model_name='station',
            name='post',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='駅郵便番号'),
        ),
        migrations.AlterField(
            model_name='station',
            name='pref_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ekimei.Prefecture', verbose_name='都道府県'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_cd',
            field=models.IntegerField(default=0, unique=True, verbose_name='駅コード'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_g_cd',
            field=models.IntegerField(default=0, verbose_name='駅グループコード'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=200, verbose_name='駅名'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name_k',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(カナ)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name_r',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='駅名(ローマ字)'),
        ),
    ]
