# Generated by Django 2.0.13 on 2019-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0014_auto_20190531_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tieup',
            field=models.CharField(blank=True, max_length=200, verbose_name='タイアップ等'),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='備考'),
        ),
    ]
