# Generated by Django 2.0.13 on 2019-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekimei', '0015_auto_20190531_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, to='ekimei.Artist'),
        ),
    ]
